resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:078d46be88244e200bd38542910acd074930eeb0b565d2613adb8db76981beff
  name: operator
  newName: registry.redhat.io/openshift-builds/openshift-builds-rhel9-operator
