apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Full Lifecycle
    categories: Developer Tools, Integration & Delivery
    certified: "true"
    description: Builds for Red Hat OpenShift is a framework for building container
      images on Kubernetes.
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "true"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "true"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openshift-builds
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift
      Platform Plus"]'
    operators.operatorframework.io/internal-objects: '["openshiftbuilds.operator.openshift.io","shipwrightbuilds.operator.shipwright.io"]'
    repository: https://github.com/shipwright-io/operator
    support: Red Hat
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
  name: openshift-builds-operator.v0.0.0
  namespace: openshift-builds
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ShipwrightBuild represents the deployment of Shipwright's build
        controller on a Kubernetes cluster.
      displayName: Shipwright Build
      kind: ShipwrightBuild
      name: shipwrightbuilds.operator.shipwright.io
      version: v1alpha1
    - description: OpenShiftBuild describes the desired state of Builds for OpenShift,
        and the status of all deployed components.
      displayName: Open Shift Build
      kind: OpenShiftBuild
      name: openshiftbuilds.operator.openshift.io
      version: v1alpha1
    required:
    - kind: TektonConfig
      name: tektonconfigs.operator.tekton.dev
      version: v1alpha1
  description: "Builds for Red Hat OpenShift is an extensible build framework based
    on the Shipwright project, \nwhich you can use to build container images on an
    OpenShift Container Platform cluster. \nYou can build container images from source
    code and Dockerfile by using image build tools, \nsuch as Source-to-Image (S2I)
    and Buildah. You can create and apply build resources, view logs of build runs,
    \nand manage builds in your OpenShift Container Platform namespaces.\nRead more:
    [https://shipwright.io](https://shipwright.io)\n\n## Features\n\n* Standard Kubernetes-native
    API for building container images from source code and Dockerfile\n\n* Support
    for Source-to-Image (S2I) and Buildah build strategies\n\n* Extensibility with
    your own custom build strategies\n\n* Execution of builds from source code in
    a local directory\n\n* Shipwright CLI for creating and viewing logs, and managing
    builds on the cluster\n\n* Integrated user experience with the Developer perspective
    of the OpenShift Container Platform web console\n"
  displayName: Builds for Red Hat OpenShift Operator
  icon:
  - base64data: |
      PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDM4IDM4Ij48ZGVmcz48c3R5bGU+LmN7ZmlsbDojZTAwO30uZHtmaWxsOiNmZmY7fS5le2ZpbGw6I2UwZTBlMDt9PC9zdHlsZT48L2RlZnM+PGcgaWQ9ImEiPjxnPjxyZWN0IGNsYXNzPSJkIiB4PSIxIiB5PSIxIiB3aWR0aD0iMzYiIGhlaWdodD0iMzYiIHJ4PSI5IiByeT0iOSIvPjxwYXRoIGNsYXNzPSJlIiBkPSJNMjgsMi4yNWM0LjI3LDAsNy43NSwzLjQ4LDcuNzUsNy43NVYyOGMwLDQuMjctMy40OCw3Ljc1LTcuNzUsNy43NUgxMGMtNC4yNywwLTcuNzUtMy40OC03Ljc1LTcuNzVWMTBjMC00LjI3LDMuNDgtNy43NSw3Ljc1LTcuNzVIMjhtMC0xLjI1SDEwQzUuMDMsMSwxLDUuMDMsMSwxMFYyOGMwLDQuOTcsNC4wMyw5LDksOUgyOGM0Ljk3LDAsOS00LjAzLDktOVYxMGMwLTQuOTctNC4wMy05LTktOWgwWiIvPjwvZz48L2c+PGcgaWQ9ImIiPjxnPjxjaXJjbGUgY2xhc3M9ImQiIGN4PSIxOSIgY3k9IjE5IiByPSI3LjM4Ii8+PHBhdGggY2xhc3M9ImMiIGQ9Ik0xOSwxMC4zOGMtNC43NiwwLTguNjIsMy44Ny04LjYyLDguNjJzMy44Nyw4LjYyLDguNjIsOC42Miw4LjYyLTMuODcsOC42Mi04LjYyLTMuODctOC42Mi04LjYyLTguNjJabTAsMTZjLTQuMDcsMC03LjM4LTMuMzEtNy4zOC03LjM4czMuMzEtNy4zOCw3LjM4LTcuMzgsNy4zOCwzLjMxLDcuMzgsNy4zOC0zLjMxLDcuMzgtNy4zOCw3LjM4WiIvPjwvZz48Zz48cGF0aCBjbGFzcz0iZCIgZD0iTTE1LjM4LDE2YzAtLjM1LC4yOC0uNjIsLjYyLS42Mmg1LjM4di00Ljc1SDEwLjYydjEwLjc1aDQuNzV2LTUuMzhaIi8+PHJlY3QgY2xhc3M9ImQiIHg9IjE2LjYyIiB5PSIxNi42MiIgd2lkdGg9IjEwLjc1IiBoZWlnaHQ9IjEwLjc1Ii8+PHBhdGggZD0iTTI4LDE1LjM4aC01LjM4di01LjM4YzAtLjM1LS4yOC0uNjItLjYyLS42MkgxMGMtLjM1LDAtLjYyLC4yOC0uNjIsLjYydjEyYzAsLjM1LC4yOCwuNjIsLjYyLC42Mmg1LjM4djUuMzhjMCwuMzUsLjI4LC42MiwuNjIsLjYyaDEyYy4zNCwwLC42Mi0uMjgsLjYyLS42MnYtMTJjMC0uMzUtLjI4LS42Mi0uNjItLjYyWm0tLjYyLDEyaC0xMC43NXYtMTAuNzVoMTAuNzV2MTAuNzVaTTEwLjYyLDEwLjYyaDEwLjc1djQuNzVoLTUuMzhjLS4zNSwwLS42MiwuMjgtLjYyLC42MnY1LjM4aC00Ljc1VjEwLjYyWiIvPjwvZz48Zz48cG9seWdvbiBjbGFzcz0iZCIgcG9pbnRzPSIxOS44OCAyMiAyMSAyMy4xMiAyMSAyMC44OCAxOS44OCAyMiIvPjxwYXRoIGNsYXNzPSJjIiBkPSJNMjEsMjAuODhsLjQ0LS40NGMuMjQtLjI0LC4yNC0uNjQsMC0uODgtLjI0LS4yNC0uNjQtLjI0LS44OCwwbC0yLDJjLS4yNCwuMjQtLjI0LC42NCwwLC44OGwyLDJjLjEyLC4xMiwuMjgsLjE4LC40NCwuMThzLjMyLS4wNiwuNDQtLjE4Yy4yNC0uMjQsLjI0LS42NCwwLS44OGwtLjQ0LS40NC0xLjEyLTEuMTIsMS4xMi0xLjEyWiIvPjxwb2x5Z29uIGNsYXNzPSJkIiBwb2ludHM9IjIzIDIwLjg4IDIzIDIzLjEyIDI0LjEyIDIyIDIzIDIwLjg4Ii8+PHBhdGggY2xhc3M9ImMiIGQ9Ik0yNS40NCwyMS41NmwtMi0yYy0uMjQtLjI0LS42NC0uMjQtLjg4LDAtLjI0LC4yNC0uMjQsLjY0LDAsLjg4bC40NCwuNDQsMS4xMiwxLjEyLTEuMTIsMS4xMi0uNDQsLjQ0Yy0uMjQsLjI0LS4yNCwuNjQsMCwuODgsLjEyLC4xMiwuMjgsLjE4LC40NCwuMThzLjMyLS4wNiwuNDQtLjE4bDItMmMuMjQtLjI0LC4yNC0uNjQsMC0uODhaIi8+PC9nPjwvZz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - build
  - shipwright
  - tekton
  - cicd
  links:
  - name: Documentation
    url: https://docs.redhat.com/en/documentation/builds_for_red_hat_openshift/1.2
  - name: Builds for Openshift
    url: https://github.com/redhat-openshift-builds/operator
  maintainers:
  - email: support@redhat.com
    name: Red Hat OpenShift Builds Team
  maturity: stable
  minKubeVersion: 1.25.0
  provider:
    name: Red Hat
    url: https://www.redhat.com
  relatedImages:
  - image: registry.redhat.io/openshift-builds/openshift-builds-rhel9-operator@sha256:1f4bb11f97158b3a4fe0aa34eca7ec7e9e568c42e559e9c1864c0586504a51d1
    name: OPENSHIFT_BUILDS_OPERATOR
  - image: registry.redhat.io/openshift-builds/openshift-builds-controller-rhel9@sha256:8ff35f843458754b75d8fb5b554c174be72a4eba043aa7b4e44adfe119d3a1e0
    name: OPENSHIFT_BUILDS_CONTROLLER
  - image: registry.redhat.io/openshift-builds/openshift-builds-git-cloner-rhel9@sha256:fc187ff9aa8375fe65ac64388563ff522e4aa1ba8cd69485c390090e924ef006
    name: OPENSHIFT_BUILDS_GIT_CLONER
  - image: registry.redhat.io/openshift-builds/openshift-builds-image-processing-rhel9@sha256:1064515dc5e61b444dcab6fae0a0757331a4b4cf1af088c5361c9974fc97ed29
    name: OPENSHIFT_BUILDS_IMAGE_PROCESSING
  - image: registry.redhat.io/openshift-builds/openshift-builds-image-bundler-rhel9@sha256:c4e0b8b8b1b4c28e642f2fd35d822a740fb3378a0bd75380cf4c6367c92028c4
    name: OPENSHIFT_BUILDS_IMAGE_BUNDLER
  - image: registry.redhat.io/openshift-builds/openshift-builds-waiters-rhel9@sha256:c69f046a0c27c6e388be6d86e7237452ab620350b7488559d448f9dd923b41b1
    name: OPENSHIFT_BUILDS_WAITER
  - image: registry.redhat.io/openshift-builds/openshift-builds-webhook-rhel9@sha256:576d8638970f6bcce3954af8fdb319ef47cf27169945748369c0a753a34de5c1
    name: OPENSHIFT_BUILDS_WEBHOOK
  - image: registry.redhat.io/openshift-builds/openshift-builds-shared-resource-webhook-rhel9@sha256:b900e8001bcf444a395b212eb767462c32bb646ebe1dbc4dae7b437779b5b344
    name: OPENSHIFT_BUILDS_SHARED_RESOURCE_WEBHOOK
  - image: registry.redhat.io/openshift-builds/openshift-builds-shared-resource-rhel9@sha256:56b92b7fa0ea54e64ed7b71990ed41b4f47fe77af9fe80f6ebc8f11fba5b23e8
    name: OPENSHIFT_BUILDS_SHARED_RESOURCE
  - image: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel9@sha256:e8582857566020c71653228355cbadc2c1cda41e36fc767c204a4edb05e7f42a
    name: OPENSHIFT_BUILDS_SHARED_RESOURCE_NODE_REGISTRAR
  - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9@sha256:3fa22124916523b958c67af8ad652e73a2c3d68bb5579da1cba1ade537f3b7ae
    name: OPENSHIFT_BUILDS_KUBE_RBAC_PROXY
  - image: registry.redhat.io/ubi8/buildah@sha256:56c71ecd450f284325ba8434cbf5b3006078b11f0625c6258689699fa811c95d
    name: OPENSHIFT_BUILDS_BUILDAH
  - image: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:016c93578908f1dbdc3052333a1d5a9ab0c03104070ac36a6ddf99350d7510f4
    name: OPENSHIFT_BUILDS_SOURCE_TO_IMAGE
  version: 1.2.1
